-- Applied to test-artesao / fpjxixijldymlkajenck as migration 20260912131812.
-- Persists old public-media paths transactionally so failed Storage removals can be retried.
create table private.media_cleanup_queue (
  id bigint generated by default as identity primary key,
  object_path text not null unique
    check (char_length(object_path) between 1 and 1024 and object_path !~ '(^|/)\.\.?(/|$)'),
  source_table text not null
    check (source_table in ('artisans','works','artisan_media','work_media')),
  source_id uuid not null,
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table private.media_cleanup_queue enable row level security;
revoke all on private.media_cleanup_queue from public, anon, authenticated;
grant select, insert, update, delete on private.media_cleanup_queue to service_role;
grant usage, select on sequence private.media_cleanup_queue_id_seq to service_role;

create or replace function private.queue_replaced_public_media()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  old_url text;
  new_url text;
  queued_path text;
  record_id uuid;
begin
  if tg_table_schema <> 'public' then
    raise exception 'Unexpected trigger source';
  end if;

  if tg_table_name = 'artisans' then
    old_url := old.portrait_url;
    record_id := old.id;
    if tg_op = 'UPDATE' then new_url := new.portrait_url; end if;
  elsif tg_table_name = 'works' then
    old_url := old.cover_url;
    record_id := old.id;
    if tg_op = 'UPDATE' then new_url := new.cover_url; end if;
  elsif tg_table_name = 'artisan_media' then
    old_url := old.url;
    record_id := old.artisan_id;
    if tg_op = 'UPDATE' then new_url := new.url; end if;
  elsif tg_table_name = 'work_media' then
    old_url := old.url;
    record_id := old.work_id;
    if tg_op = 'UPDATE' then new_url := new.url; end if;
  else
    raise exception 'Unexpected trigger table';
  end if;

  if old_url is not null and old_url is distinct from new_url
     and position('/storage/v1/object/public/public-media/' in old_url) > 0 then
    queued_path := split_part(
      split_part(old_url, '/storage/v1/object/public/public-media/', 2),
      '?',
      1
    );
    if char_length(queued_path) between 1 and 1024
       and queued_path !~ '(^|/)\.\.?(/|$)' then
      insert into private.media_cleanup_queue(object_path, source_table, source_id)
      values(queued_path, tg_table_name, record_id)
      on conflict(object_path) do update set
        source_table = excluded.source_table,
        source_id = excluded.source_id,
        last_error = null,
        updated_at = now();
    end if;
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end
$$;
revoke all on function private.queue_replaced_public_media() from public, anon, authenticated, service_role;

drop trigger if exists queue_artisan_portrait_update on public.artisans;
create trigger queue_artisan_portrait_update
after update of portrait_url on public.artisans
for each row when (old.portrait_url is distinct from new.portrait_url)
execute function private.queue_replaced_public_media();

drop trigger if exists queue_artisan_portrait_delete on public.artisans;
create trigger queue_artisan_portrait_delete
after delete on public.artisans
for each row execute function private.queue_replaced_public_media();

drop trigger if exists queue_work_cover_update on public.works;
create trigger queue_work_cover_update
after update of cover_url on public.works
for each row when (old.cover_url is distinct from new.cover_url)
execute function private.queue_replaced_public_media();

drop trigger if exists queue_work_cover_delete on public.works;
create trigger queue_work_cover_delete
after delete on public.works
for each row execute function private.queue_replaced_public_media();

drop trigger if exists queue_artisan_media_update on public.artisan_media;
create trigger queue_artisan_media_update
after update of url on public.artisan_media
for each row when (old.url is distinct from new.url)
execute function private.queue_replaced_public_media();

drop trigger if exists queue_artisan_media_delete on public.artisan_media;
create trigger queue_artisan_media_delete
after delete on public.artisan_media
for each row execute function private.queue_replaced_public_media();

drop trigger if exists queue_work_media_update on public.work_media;
create trigger queue_work_media_update
after update of url on public.work_media
for each row when (old.url is distinct from new.url)
execute function private.queue_replaced_public_media();

drop trigger if exists queue_work_media_delete on public.work_media;
create trigger queue_work_media_delete
after delete on public.work_media
for each row execute function private.queue_replaced_public_media();

create or replace function public.read_media_cleanup(p_limit integer default 100)
returns table(id bigint, object_path text)
language plpgsql
security invoker
set search_path=''
as $$
begin
  if coalesce(auth.jwt()->>'role','') <> 'service_role' then
    raise exception 'Forbidden';
  end if;
  if p_limit not between 1 and 100 then
    raise exception 'Invalid limit';
  end if;
  return query
    select q.id, q.object_path
    from private.media_cleanup_queue q
    order by q.attempts, q.created_at
    limit p_limit;
end
$$;
revoke all on function public.read_media_cleanup(integer) from public, anon, authenticated;
grant execute on function public.read_media_cleanup(integer) to service_role;

create or replace function public.finish_media_cleanup(p_ids bigint[], p_error text default null)
returns integer
language plpgsql
security invoker
set search_path=''
as $$
declare changed integer;
begin
  if coalesce(auth.jwt()->>'role','') <> 'service_role' then
    raise exception 'Forbidden';
  end if;
  if p_ids is null or cardinality(p_ids) not between 1 and 100 then
    raise exception 'Invalid identifiers';
  end if;
  if p_error is null then
    delete from private.media_cleanup_queue where id = any(p_ids);
  else
    update private.media_cleanup_queue
    set attempts = attempts + 1,
        last_error = left(p_error, 500),
        updated_at = now()
    where id = any(p_ids);
  end if;
  get diagnostics changed = row_count;
  return changed;
end
$$;
revoke all on function public.finish_media_cleanup(bigint[],text) from public, anon, authenticated;
grant execute on function public.finish_media_cleanup(bigint[],text) to service_role;
